import {UserToUserContext} from "./UserToUserContext";

export interface GeneralUser {
    membershipId: string,
    uniqueName: string,
    normalizedName: string,
    displayName: string,
    profilePicture: number,
    profileTheme: number,
    userTitle: number,
    successMessageFlags: string,
    isDeleted: boolean,
    about: string,
    firstAccess?: string,
    lastUpdate?: string,
    legacyPortalUID?: string,
    context: UserToUserContext,
    psnDisplayName: string,
    xboxDisplayName: string,
    fbDisplayName: string,
    showActivity?: boolean,
    locale: string,
    localeInheritDefault: boolean,
    lastBanReportId?: string,
    showGroupMessaging: boolean,
    profilePicturePath: string,
    profilePictureWidePath: string,
    profileThemeName: string,
    userTitleDisplay: string,
    statusText: string,
    statusDate: string,
    profileBanExpire: string,
    blizzardDisplayName: string,
    steamDisplayName: string,
    stadiaDisplayName: string,
    twitchDisplayName: string
}